config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'races#index', defaults: { category: :all }

  resources :users do
    get 'account'
    get 'histories(/:type)', to: 'histories#index', as: 'histories', defaults: { type: :all }
    get 'import'
  end

  get 'races(/category/:category)', to: 'races#index', as: 'races', defaults: { category: :all }
  resources :races, except: :index do
    put 'start', to: 'races#start'
    member do
      get :data_series
      get :chat_members
    end
    resources :lanes, param: :lane_id do
      post 'offers', to: 'offers#create', as: 'offers'
    end
    put 'oracle/:user_id', to: 'races#assign_to_oracle', as: 'assign_to_oracle'
  end

  scope :chat_rooms, defaults: { format: :json } do
    get ':race_id/join/:user_id', to: 'chat_rooms#join'
    get ':race_id/user_info/:user_id', to: 'chat_rooms#user_info'
    get ':race_id/update', to: 'chat_rooms#update'
  end

  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get 'auth/failure', to: redirect('/')

  resources :user_activations, only: [:edit]
  resources :reset_password, only: [:new, :create, :edit, :update]

  namespace :admin do
    root to: 'races#index'
    resources :races, only: [:index, :show]
    resources :users, only: [:index, :show, :edit]
  end

  resources :transactions

  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'
end

app/controllers/reset_password_controller.rb
class ResetPasswordController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new; end

  def create
    @user = User.login_by_email.find_by(email: params[:reset_password][:email].downcase)
  rescue Mongoid::Errors::DocumentNotFound
    flash[:danger] = "Email address not found"
    render 'new'
  else
    @user.create_reset_digest
    @user.send_reset_password_email
    flash[:info] = "Email sent with password reset instructions"
    redirect_to root_url
  end

  def edit; end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      @user.update(:reset_digest, nil)
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def get_user
    @user = User.find_by(email: params[:email])
  end

  def valid_user
    unless @user&.activaed? and @user.authenticated?(:reset, params[:id])
      redirect_to root_url
    end
  end

  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "Password reset has expired."
      redirect_to new_reset_password_url
    end
  end
end

app/helpers/reset_password_helper.rb
module ResetPasswordHelper
end

app/views/reset_password/edit.html.erb
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3"> 
    <%= form_for(@user, url: reset_password_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %> 
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %> 
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/reset_password/new.html.erb
<h1>Forgot Password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with scope: :reset_password, url: reset_password_index_path, local: true do |form| %>

      <div class="form-group">
        <%= form.label :email, class: "sr-only" %>
        <%= form.email_field :email, id: 'reset_password_email', class: 'form-control', placeholder: 'Email' %>
      </div>
      <%= form.submit "Submit", class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>