config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'races#index', defaults: { category: :all }

  resources :users do
    get 'account'
    get 'histories(/:type)', to: 'histories#index', as: 'histories', defaults: { type: :all }
    get 'import'
  end

  get 'races(/category/:category)', to: 'races#index', as: 'races', defaults: { category: :all }
  resources :races, except: :index do
    put 'start', to: 'races#start'
    member do
      get :data_series
      get :chat_members
    end
    resources :lanes, param: :lane_id do
      post 'offers', to: 'offers#create', as: 'offers'
    end
    put 'oracle/:user_id', to: 'races#assign_to_oracle', as: 'assign_to_oracle'
  end

  scope :chat_rooms, defaults: { format: :json } do
    get ':race_id/join/:user_id', to: 'chat_rooms#join'
    get ':race_id/user_info/:user_id', to: 'chat_rooms#user_info'
    get ':race_id/update', to: 'chat_rooms#update'
  end

  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get 'auth/failure', to: redirect('/')

  resources :user_activations, only: [:edit]
  resources :reset_password, only: [:new, :create, :edit, :update]

  namespace :admin do
    root to: 'races#index'
    resources :races, only: [:index, :show]
    resources :users, only: [:index, :show, :edit]
  end

  resources :transactions

  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'
end

app/models/race.rb
class Race
  include Mongoid::Document
  include Mongoid::Timestamps
  extend SimplestStatus

  before_save { self.title = title.strip }
  before_create { self.is_test = self.host.is_tester }

  field :title, type: String
  field :description, type: String
  field :rule, type: Integer, default: 0
  field :time_zone, type: String
  field :initial_lot, type: BigDecimal, default: MY_APP[:initial_lot_per_lane]
  field :status, type: Integer, default: 0
  field :start_datetime, type: DateTime, default: Time.now
  field :end_datetime, type: DateTime, default: Time.now
  field :youtube_url, type: String
  field :member_ids, type: Array, default: []
  belongs_to :host, class_name: 'User'
  belongs_to :oracle, class_name: 'User', optional: true
  has_many :lanes, dependent: :destroy, inverse_of: :race
  belongs_to :category
  mount_uploader :picture, PictureUploader
  field :hidden, type: Boolean, default: false
  field :is_test, type: Boolean, default: false

  simple_status :rule, %i(winner_takes_all vote_share)
  statuses :preparing, :ready, :racing, :pending, :closed
  validates :title, presence: true
  # validate :start_datetime_greater_than_now
  validate :end_datetime_should_be_greater_than_start_datetime
  validates :youtube_url, youtube_url: true, allow_blank: true

  default_scope -> { order_by(created_at: :desc) }
  scope :tests, -> { where(is_test: true) }
  scope :by_category, -> (category=:all) { where(category: category) unless category == :all }
  paginates_per 10

  # Check status
  def prepared?
    not preparing?
  end

  # Related with process

  def prepare!
    raise NoLanesError if lanes.length < 2
    initial_price = 1.0 / lanes.size * 100
    initial_volume = initial_lot * initial_price

    lanes.update_all(lot: initial_lot,
                     price: initial_price,
                     volume: initial_volume)
    lanes.each { |lane| lane.reload }
    self.ready
  end

  # Ranking of lanes

  def winner=(lane)
    lanes.update_all(is_winner: false)
    lane.update(is_winner: true)
  end

  def winner
    lanes.find_by(is_winner: true)
  end

  def losers
    lanes.where(is_winner: false)
  end

  def top_lane
    lanes.order(price: :desc).first
  end

  # Related with trade

  def total_lots
    lanes.sum(&:lot)
  end

  def complete_trade(offer)
    adjust_prices_of_lanes
  end

  def payoff
    case rule
    when WINNER_TAKES_ALL
      @payoffer = WTAOfficer.new(self)
    when VOTE_SHARE
      @payoffer = VSOfficer.new(self)
    end
    @payoffer.execute
  end

  # Related with operators

  def host?(user)
    host == user
  end

  def oracle?(user)
    oracle == user
  end

  # Related with members

  def members
    User.in(id: member_ids)
  end

  def add_member(user)
    member_ids << user.id unless member?(user)
  end

  def remove_member(user)
    member_ids.delete user.id
  end

  def member?(user)
    member_ids.include? user.id
  end

  # Related with views

  def info_for_user(user)
    info = []  
    info.tap do |arr|
      arr << :closed if closed?
      arr <<  user_info(user)
    end
  end

  def user_info(user)
    if host?(user)
      :host
    elsif oracle?(user)
      :oracle
    elsif member?(user)
      :member
    end
  end

  def youtube_id
    Youtube.build(youtube_url)&.id if youtube_url
  end

  def data_points
    lanes.map do |lane|
      { type: 'line', name: lane.title, showInLegend: true, xValueType: 'dateTime', dataPoints: lane.data_points }
    end
  end

  def dday
    if Time.now < start_datetime
      (Date.today...end_datetime.to_date).count
    else
      nil
    end
  end

  private

  def adjust_prices_of_lanes
    tmp_total_lots = total_lots
    lanes.each do |lane|
      lane.reload
      lane.price = lane.lot / tmp_total_lots * 100 # TODO: calculate_price with caution
      lane.save
    end
  end

  def end_datetime_should_be_greater_than_start_datetime
    if end_datetime < start_datetime
      errors.add(:end_datetime, "should be greater than start time." )
    end
  end

  def start_datetime_greater_than_now
    if not published? and start_datetime < Time.now
      errors.add(:start_datetime, "should be greater than now.")
    end
  end
end

class Race::NoLanesError < StandardError
  def initialize(msg="There is no lane.")
    super(msg)
  end
end

app/controllers/admin/races_controller.rb
class Admin::RacesController < Admin::BaseController
  def index
    @races = Race.page(params[:page]).per(10)
  end

  def show
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy, :data_series, :host_user, :chat_members]
  before_action :logged_in_user, except: [:index, :data_series]
  before_action :host_user, only: [:edit, :update, :destroy]

  def index
    category = Category.where(name: params[:category]).first || :all

    # check that user is tester or not
    if current_user&.is_tester
      @races = Race.by_category(category).page(params[:page])
    else
      @races = Race.by_category(category).not.tests.page(params[:page])
    end
    
    render layout: 'races/index'
  end

  def show
    @race.add_member current_user
    @race.save
    if @race.preparing?
      render :show
    else
      render :race_show
    end
  end

  def new
    @race = Race.new

    @title_bar = 'new race'
    render layout: 'detail'
  end

  def edit
  end

  def create
    @race = Race.new(race_params)
    @race.tap do |race|
      race.start_datetime = composite_datetime(params[:start], race_params[:time_zone])
      race.end_datetime = composite_datetime(params[:end], race_params[:time_zone])
      race.host = current_user
      race.add_member current_user
    end

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, flash: {success: 'Race was successfully created.'} }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @race.tap do |race|
      race.start_datetime = composite_datetime(params[:start], race_params[:time_zone])
      race.end_datetime = composite_datetime(params[:end], race_params[:time_zone])
    end

    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, flash: {success: 'Race was successfully updated.'} }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @race.destroy
    respond_to do |format|
      format.html do
        redirect_to races_url, flash: { success: 'Race was successfully destroyed.' }
      end
      format.json { head :no_content }
    end
  end

  def start
    @race = Race.find(params[:race_id])
    @race.prepare!
  rescue Race::NoLanesError
    flash[:danger] = "Failed to start. Race should have lanes."
  else
    open_chat.call
  ensure
    redirect_to @race
  end

  def data_series
    render json: @race.data_points
  end

  def chat_members
    
  end

  def assign_to_oracle
    return unless admin?

    @race = Race.find(params[:race_id])
    user = User.find(params[:user_id] || current_user.id)
    @race.tap do |race|
      race.oracle = user
      race.add_member user
      race.save
    end
  end

  private

  def set_race
    @race = Race.find(params[:id])
  end

  def race_params
    params.require(:race).permit(:title, :description, :rule, :time_zone, :start_datetime, :end_datetime, :picture, :picture_cache, :youtube_url, :category_id)
  end

  def open_chat
    ChatRoom::Open.new(
      user_id: current_user.id,
      user_name: current_user.name,
      race_title: @race.title,
      race_id: @race.id,
      max_people: 1000)
  end

  def host_user
    return if admin?
    
    unless @race.host? current_user
      flash[:danger] = "You're not the host."
      redirect_to race_path
    end
  end

end

app/helpers/admin/races_helper.rb
module Admin::RacesHelper
end

app/helpers/races_helper.rb
module RacesHelper
  def chat_iframe(url)
    content_tag :iframe, id: 'chat_frame', name: 'chat_frame', data: { src: url }, scrolling: 'auto', frameborder: 0 do
      content_tag :p, "Your browser doesn't support iframes."
    end
  end

  def operator?(user: current_user)
    return unless current_user
    user.is_admin? or @race.host == user
  end

  def host?(user: current_user)
    return unless current_user
    user == self.host
  end

  def offset_datetime(datetime, zone)
    return DateTime.now if datetime.nil?
    return datetime if zone.nil?
    utc_offset = ActiveSupport::TimeZone.new(zone).formatted_offset
    datetime.localtime(utc_offset)
  end
end

app/views/races/_chart_container.html.erb
<%= content_tag :div, nil, id: 'chartContainer', data: { started: true, race: @race.id.to_s } %>

app/views/races/_chat.html.erb
<div class="pm-chat-contents"> 
  <%= chat_iframe join_chat_url(race, current_user) if race.prepared? and current_user %>
</div>

app/views/races/_form.html.erb
<%= form_with model: @race, local: true, id: "race_form" do |form| %>
	<% if race.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(race.errors.count, "error") %> prohibited this race from being saved:</h2>

			<ul>
				<% race.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= form.label :title, class: 'sr-only' %>
		<%= form.text_field :title, id: :race_title, class: 'form-control', placeholder: 'Title' %>
	</div>

	<div class="form-group">
		<%= form.label :description, class: 'sr-only' %>
		<%= form.text_area :description, id: :race_description, class: 'form-control', rows: 10, placeholder: 'Description' %>
	</div>

	<div class="form-horizontal">
		<div class="form-group">
			<%= form.label :rule, class: "col-xs-3 control-label" %>
			<div class="col-xs-9">
				<%= form.select :rule, Race.rules.for_select, {}, { class: 'form-control' } %>
			</div>
		</div>

		<div class="form-group">
			<%= form.label :start_datetime, 'Start Date', class: "col-xs-3 control-label" %>
      <div class="col-xs-9">
        <%= date_field_tag 'start[date]', offset_datetime(@race.start_datetime, @race.time_zone).to_date %>
        <%= select_time offset_datetime(@race.start_datetime, @race.time_zone), prefix: 'start', minute_step: 5 %>
			</div>
		</div>

		<div class="form-group">
			<%= form.label :end_datetime, 'End Date', class: "col-xs-3 control-label" %>
      <div class="col-xs-9">
        <%= date_field_tag 'end[date]', offset_datetime(@race.end_datetime, @race.time_zone).to_date %>
        <%= select_time offset_datetime(@race.end_datetime, @race.time_zone), prefix: 'end', minute_step: 5 %>
			</div>
		</div>

		<div class="form-group">
			<%= form.label :time_zone, class: "col-xs-3 control-label" %>
			<div class="col-xs-9">
				<%= form.time_zone_select :time_zone, nil, { default: "Seoul" }, { class: 'form-control' } %>
			</div>
		</div>

		<div class="form-group">
			<%= form.label :category, class: "col-xs-3 control-label" %>
			<div class="col-xs-9">
				<%= form.collection_select :category_id, Category.all, :id, :name, { include_blank: true }, { class: 'form-control' } %>
			</div>
		</div>

		<% if race.picture? %>
			<p class="center-block">
			<%= image_tag(race.picture_url, class: 'img-responsive') %>
			</p>
		<% end %>

		<div class="form-group">
			<%= form.label :picture, glyphicon('picture', label: 'picture'), class: "col-xs-3 control-label" %>
			<div class="col-xs-9">
				<%= form.file_field :picture, id: :race_picture, accept: 'image/jpeg, image/png, image/gif' %>
			</div>
			<%= form.hidden_field :picture_cache %>
		</div>

		<div class="form-group">
			<%= form.label :youtube_url, glyphicon('facetime-video', label: 'youtube url'), class: "col-xs-3 control-label" %>
			<div class="col-xs-9">
				<%= form.url_field :youtube_url, id: :race_youtube_url, class: 'form-control', placeholder: 'https://youtube.com/' %>
			</div>
		</div>
	</div>

	<%= form.submit class: 'btn btn-primary btn-block btn-lg' %>
<% end %>

app/views/races/_my_races.html.erb
<% races.each do |race| %>
  <div> 
    <% race.info_for_user(current_user).each do |info| %>
      <span class="label label-default text-uppercase pm-label-round pm-label-<%= info %>" >
        <%= info %>
      </span>
    <% end %>
    <h3 class="h5">
      <%= link_to race.title, race, class: "text-default" %>
    </h3>
    <hr>
  </div>
<% end %>

app/views/races/_race_large.html.erb
<div id="race_top_buttons">
  <a id="close_large" href="#">
    <i class="glyphicon glyphicon-remove"></i>
  </a>
</div>

<h1 class="page-header pm-page-title"> 
  <%= race.title %>
  <span class="label label-default pull-right pm-label-dday"><%= "D-#{race.dday}" if race.dday %></span>
</h1>

<%#= render template: 'races/show', race: @race %>
<!-- lanes list -->
<% length = @race.lanes.length %>
<div class="panel-group pm-lane-group" role="tablist" aria-multiselectable="true" id="lanes_list" data-length="<%= race.lanes.length %>">
  <%= render @race.lanes %>
</div>
<div id="lane_form"></div>

<h2 class="h5 text-uppercase">Total IN</h2>
<p class="text-uppercase pm-text-emphasis"> 
<span class="h4"><%= volume_with_format race.lanes.sum(&:in_volume) %></span><small> D</small>
<% total_in_lots = race.lanes.sum(&:in_lot) %><br>
<span class="h4"><%= lot_with_format(total_in_lots) %></span><small> lots</small><br>
<hr>
available IN in this race:
<span class="h4"><%= lot_with_format(MY_APP[:investment_limit] - total_in_lots) %></span><small> lots</small>
<br><span><%= volume_with_format current_user.current_balance %><span class="small text-muted"> D</span></span>
</p>

<%#= render 'chart_container' if race.prepared? %>

<h2 class="h5 text-uppercase">race info</h2>
<ul class="pm-race-info-list small text-uppercase text-strong">
  <li><span class="text-muted">length: </span><span><%= "#{localtime(race.start_datetime)} ~ #{localtime(race.end_datetime)}" %></span></li>
  <li><span class="text-muted">rule: </span><span><%= race.rule_label.upcase %></span></li>
  <li><span class="text-muted">host: </span><span><%= race.host.name %></span></li>
  <%# <li><span class="text-muted">oracle: </span><span class="pm-text-emphasis">[ game38 ]</span></li> %>
  <li><span class="text-muted">MEMBERS:</span> <%= number_with_delimiter race.members.length %></li>
  <li><span class="text-muted">MY IN:</span> <%= "#{lot_with_format current_user.lots_for_each_lane(race.lane_ids).inject(0) { |sum, item| sum += item[1] }} LOTS" %></li>
</ul>

<div>
  <%= image_tag(race.picture_url, class: 'img-responsive img-thumbnail pm-img-detail') if race.picture? %>
  <%= youtube_iframe race.youtube_id if race.youtube_id %> 
</div>

<p class="small pm-race-description">
<%= simple_format race.description %>
</p>

<% if admin? %>
  <%= link_to 'Edit', edit_race_path(@race) %> |
  <%= link_to 'Destroy', @race, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/races/_race_regular.html.erb
<h1 class="pm-page-title">
  <%= truncate race.title, length: 100 %>
</h1>
<hr>

<%= content_tag :div, id: "lanes_regular_list", data: { length: @race.lanes.count(limit: 3) } do %>
  <% race.lanes.order_by(price: :desc).limit(3).each_with_index do |lane, index| %>
    <div class="pm-lane-info">
    <%= content_tag :div, nil, id: "lane_chart_default_#{index}", class: 'lane-chart clearfix inline-block', data: { percent: lane.price } %>
    <strong class="pm-text-percent">
      <%= price_with_format lane.price %>
    </strong>
    <span class="text-primary"><%= lane.title %></span>
    </div>
  <% end %>
<% end %>

app/views/races/_race_small.html.erb
<h1 class="pm-page-title"><%= race.title %></h1>

app/views/races/chat_members.js.erb
var container = $('div.pm-container-race-detail');
var div_members = container.find('#chat_members_list');
if (div_members.length) {
  div_members.show();
} else {
  container.prepend("<%= j render 'chat_members' %>");
}

app/views/races/edit.html.erb
<% content_for :navbar do %>
  <%= render 'layouts/navbar_detail', title_bar: 'Edit Race' %>
<% end %>

<div class="spacer"></div>
<%= render 'form', race: @race %>
<br>
<%= link_to 'Delete Race', @race, method: :delete, class: 'btn btn-danger btn-block btn-lg', data: { confirm: 'Are you sure?' } %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>
<div id="race_list">
  <section>
    <ul id="category_tabs" class="list-inline text-uppercase pm-race-category">
      <li role="presentation"><%= link_to 'All', races_path(:all), class: "pm-text-white", remote: false %></li>
      <% Category.each do |category| %>
        <li role="presentation"><%= link_to category.name, races_path(category.name), class: "pm-text-white", remote: false %></li>
      <% end %>
    </ul>
    <div id="races">
      <%= content_tag :ul, class: "list-group" do %>
        <%= render @races, type: :simple %>
      <% end %>
      <%= paginate @races %>
    </div>
  </section>
</div>

app/views/races/index.js.erb
$('#races > ul').html("<%= j render(@races) %>");

app/views/races/new.html.erb
<%= render 'form', race: @race %>

app/views/races/race_show.html.erb
<% content_for :navbar do %>
  <%= render 'layouts/navbar_race_detail' %>
<% end %>

<% content_for :container do %>
  <div id="chat_section" class="container pm-container-chat">
    <%= render "chat", race: @race %>
  </div>

  <div class="container pm-container-race-detail">
    <%= render "shared/main_nav" %>
    <div id="widget_small" class="pm-race-detail pm-race-detail-small">
      <%= render 'race_small', race: @race %>
    </div> 

    <div id="widget_regular" class="pm-race-detail pm-race-detail-regular">
      <%= render 'race_regular', race: @race %>
    </div>

    <div id="widget_large" class="pm-race-detail pm-race-detail-large">
      <%= render 'race_large', race: @race %>
    </div>
  </div>
<% end %>

<%= render template: 'layouts/application' %>

app/views/races/show.html.erb
<% content_for :navbar do %>
  <%= render 'layouts/navbar_detail', title_bar: main_logo_link %>
<% end %>

<h3 class="text-uppercase">Race</h3>
<h4 class="pm-race-title"><%= @race.title %></h4>
<p>
<%= simple_format @race.description %>
</p>

<% if @race.prepared? %>
  <div class="list-group-item-text pm-top-lane">
    <span>
      <%= @race.top_lane.title %>
    </span>
    <span class="pm-top-lane-chart-text pull-right">
      <%= number_to_percentage @race.top_lane.price * 100, precision: 1 %>
    </span>
  </div>
  <hr>
  <%= content_tag :p, class: "list-group-item-text" do %>
    <%= image_tag @race.host.avatar.url, class: 'img-circle pm-img-avatar-thumb' %>
    <%= content_tag :strong, @race.host.name %>
    <%= content_tag :span, " and #{@race.members.length - 1} others", class: "text-muted" %>
  <% end %>
<% end %>

<%= render 'chart_container' if @race.prepared? %>
<div>
  <% if @race.picture? %>
  <div class="spacer">
    <%= image_tag(@race.picture_url, class: 'img-responsive img-thumbnail pm-img-detail') %>
  </div>
  <% end %>
  <%= youtube_iframe @race.youtube_id if @race.youtube_id %>
</div>

<div class="spacer"></div>
<% if (operator? and @race.preparing?) or admin? %>
  <%= link_to 'Edit', edit_race_path(@race), class: 'btn btn-default' %>
<% end %>

<% if @race.preparing? and admin? %>
  <%= link_to 'Start!', race_start_path(@race), method: :put, class: 'btn btn-warning' %>
<% end %>

<% if false %>
  <%#= FIXME %>  
  <% if admin? %>
    <% if @race.oracle.nil? %>
      | <%= link_to 'Assign to Oracle', race_assign_to_oracle_path(@race, current_user), method: :put, remote: false %>
    <% else %>
    <br>
    Oracle: <%= @race.oracle.name %>
    <% end %>
  <% end %>
<% end %>

<hr>
<h3 class="text-uppercase">Lanes</h3>
<%= content_tag :div, id: "lanes_list", class: "list-group", data: { length: @race.lanes.length } do %>
  <%= render @race.lanes %>
  <% if (@race.preparing? and operator?) or admin? %>
    <p class="spacer"><%= link_to 'New Lane', new_race_lane_path(@race), class: "btn btn-primary btn-block", remote: true %></p>
  <% end %>
<% end %>

<div id="lane_form"></div>