config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'races#index', defaults: { category: :all }

  resources :users do
    get 'account'
    get 'histories(/:type)', to: 'histories#index', as: 'histories', defaults: { type: :all }
    get 'import'
  end

  get 'races(/category/:category)', to: 'races#index', as: 'races', defaults: { category: :all }
  resources :races, except: :index do
    put 'start', to: 'races#start'
    member do
      get :data_series
      get :chat_members
    end
    resources :lanes, param: :lane_id do
      post 'offers', to: 'offers#create', as: 'offers'
    end
    put 'oracle/:user_id', to: 'races#assign_to_oracle', as: 'assign_to_oracle'
  end

  scope :chat_rooms, defaults: { format: :json } do
    get ':race_id/join/:user_id', to: 'chat_rooms#join'
    get ':race_id/user_info/:user_id', to: 'chat_rooms#user_info'
    get ':race_id/update', to: 'chat_rooms#update'
  end

  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get 'auth/failure', to: redirect('/')

  resources :user_activations, only: [:edit]
  resources :reset_password, only: [:new, :create, :edit, :update]

  namespace :admin do
    root to: 'races#index'
    resources :races, only: [:index, :show]
    resources :users, only: [:index, :show, :edit]
  end

  resources :transactions

  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <span><%= pluralize(object.errors.count, "error") %> prohibited this user from being saved:</span>
    </div>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag :div, class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= message %>
  <% end %>
<% end %>

app/views/shared/_main_nav.html.erb
<div id="tracing_contents"></div>
<div id="side_nav" class="pm-side-nav">

  <% if logged_in? %>
    <div class="text-center pm-side-nav-top">
      <%= link_to user_path(current_user) do %>
        <%= image_tag current_user.avatar.url, class: "img-circle img-responsive center-block pm-img-avatar" %>
        <span><%= volume_with_format current_user.current_balance %><span class="small text-muted"> D</span></span>
        <i class="glyphicon glyphicon-menu-right pull-right pm-vertical-center"></i>
      <% end %>
    </div>

    <div class="pm-side-nav-bottom">
      <ul class="nav nav-stacked text-uppercase">
        <li>
          <%= link_to root_path, class: "text-default pm-text-white" do %>
            <i class="glyphicon glyphicon-home"></i>Home
          <% end %>
        </li>
        <li>
          <%= link_to user_account_path(current_user), class: "text-default pm-text-white" do %>
            <i class="glyphicon glyphicon-stats"></i>My Account
          <% end %>
        </li>
        <% if admin? %>
          <li>
            <%= link_to user_import_path(current_user), class: "text-default pm-text-white" do %>
              <i class="glyphicon glyphicon-import"></i>Import
            <% end %>
          </li>
        <% end %>
      </ul>
      <hr>
      <ul class="nav nav-stacked text-uppercase">
        <li>
          <%= link_to logout_path, class: "text-default pm-text-white", method: :delete do %>
            <i class="glyphicon glyphicon-log-out"></i>Sign Out
          <% end %>
        </li>
      </ul>
    </div>

  <% else %>
    <div class="pm-side-nav-bottom">
      <ul class="nav nav-stacked text-uppercase">
        <li>
          <%= link_to root_path, class: "text-default pm-text-white" do %>
            <i class="glyphicon glyphicon-home"></i>Home
          <% end %>
        </li>
        <li>
          <%= link_to login_path, class: "text-default pm-text-white" do %>
            <i class="glyphicon glyphicon-log-in"></i>Sign In
          <% end %>
        </li>
      </ul>
    </div>

  <% end %>

  <div class="pm-side-nav-bottom">
  <hr>
    <ul class="nav nav-stacked">
      <li class="unstyled">
        <%= link_to 'Terms', '', onclick: "newWindow('#{privacy_path}')" %>
        &amp; 
        <%= link_to 'Privacy', '', onclick: "newWindow('#{privacy_path}')", class: 'unstyled' %>
      </li>
    </ul>
  </div>
</div>